# ----------------------------
# Site settings
# ----------------------------
title: "Hi, I'm Tyler Priestley"
email: "tylerjpriest1228@gmail.com"
description: "I'm a data science student at ASU, and a banker for Desert Financial."
baseurl: "" # leave blank unless hosting in a subfolder
url: "https://tylerpriestley.github.io/tylerpriestley" # replace with your GitHub Pages URL or custom domain

twitter_username: "@zentza"
github_username: "tylerpriestley"

# ----------------------------
# Build settings
# ----------------------------
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

# ----------------------------
# Pagination
# ----------------------------
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

# ----------------------------
# Portfolio Settings
# ----------------------------
footer_text: '© 2025 Tyler Priestley'
admin_name: 'Tyler Priestley'
google_analytics: "" # Add your GA4 / UA ID if you want tracking
enable_contact: true  # enable a contact form

# ----------------------------
# Navigation
# ----------------------------
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/blog', text: 'Blog' }
  - { url: '/contact', text: 'Contact' }
