# ----------------------------------------
# Site Settings
# ----------------------------------------
title: "Hello. I'm Tyler Priestley."
email: "tylerjpriest1228@gmail.com"
description: "I'm a data science student at ASU and a banker at Desert Financial."
url: "https://tylerpriestley.github.io"   # Use your GitHub Pages domain here
baseurl: "/tylerpriestley"                # If this is a project repo (not username.github.io)

github_username: "tylerpriestley"
instagram_username: "turtle._.tyler"

# ----------------------------------------
# Build Settings
# ----------------------------------------
markdown: kramdown
theme: phantom
plugins:
  - jekyll-paginate

# ----------------------------------------
# Pagination Settings
# ----------------------------------------
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

# ----------------------------------------
# Phantom Theme Settings
# ----------------------------------------
footer_text: '© 2025 Tyler Priestley'
admin_name: 'Tyler Priestley'
google_analytics: ""  # Add your tracking ID if using Google Analytics
enable_contact: true  # Enables contact page (needs contact.md)

# ----------------------------------------
# Navigation Menu
# ----------------------------------------
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/contact', text: 'Contact' }
